version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672
    #username/password: guest/guest

  elasticsearch:
    image: elasticsearch:5.6-alpine
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      #- "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - node.name=elasticsearch_node_1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs

    ports:
      - 9200:9200
      - 9300:9300
