version: '3'
services:
  nacos:
    image: nacos/nacos-server:v1.4.3
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - MYSQL_MASTER_SERVICE_HOST=127.0.0.1
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=root123
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
    volumes:
      - ./data/nacos/logs/:/home/nacos/logs
      #- ./data/nacos/config:/home/nacos/conf
    ports:
      - "8848:8848"