version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: redis
    restart: always
#    networks:
#      - sc-net
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=123456
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    security_opt:
        - seccomp:unconfined
#    networks:
#      - sc-net
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123
  mongo:
    image: mongo:4.4.0
    container_name: mongo
    restart: always
    ports:
     - 27017:27017
    volumes:
     - ./data/mongodb/db:/data/db
     - ./data/mongodb/log:/var/log/mongodb
     - ./data/mongodb/config:/etc/mongo

#networks:
#  sc-net:
#    external: false